### ISSUE TITLE
License for Datasets

### ISSUE THREAD

**Issue by jdittrich** [plotly/datasets#11]
**Problem:**  If I want to use, correct, change or build upon these datasets, I don't knonw if I'm allowed to. 

**Solution:** Please provide a License like [odpl](http://opendatacommons.org/licenses/odbl/) or – to prevent further questions – a statement that usual copyright applies.

**Comment by jackparmer** [comment]
Thank you, good idea - https://github.com/plotly/datasets/blob/master/LICENSE
