### ISSUE TITLE
License mismatch (LICENSE vs README)

### ISSUE THREAD

**Issue by chendaniely** [plotly/datasets#23]
Thanks for the repo! Novel datasets are always hard to find.

The `LICENSE` file is "MIT" and the `README.md` says "GPL-3". I'm also not sure if datasets fall under a software license, but rather a creative commons one instead.

But depending on the source, the license will be different. Not sure if it makes sense to have one license for all the datasets.

**Comment by nicolaskruchten** [comment]
Fixed!

**Comment by nicolaskruchten** [comment]
Thanks for the heads-up :)
