### ISSUE TITLE
FIPS code should be updated

### ISSUE THREAD

**Issue by focalfossa** [plotly/datasets#30]
Hello, 

Please update the FIPS code for the following counties in the file 
https://github.com/plotly/datasets/blob/master/geojson-counties-fips.json

Alaska | Kusilvak should be changed from 02270 to 02158

South Dakota | Oglala Lakota should be changed from 46113 to 46102

Source: https://www.cdc.gov/nchs/nvss/bridged_race/county_geography-_changes2015.pdf

**Comment by nicolaskruchten** [comment]
Thanks for letting us know about these changes! This dataset exists for demonstration purposes rather than for any actual production or analysis use, so we're not keeping them up to date :)

**Comment by focalfossa** [comment]
So I'm assuming these changes won't be made?

**Comment by nicolaskruchten** [comment]
I don't think we'd want to change this dataset today, no.
